Add a few iCalendar properties
lpil/icalendar pull request #24
Opened 2018-01-14 21:04 UTC by tcitworld

* [Status](https://tools.ietf.org/html/rfc5545#section-3.8.1.11), which matches to atoms
* [Categories](https://tools.ietf.org/html/rfc5545#section-3.8.1.2), which matches to a list of strings
* [Class](https://tools.ietf.org/html/rfc5545#section-3.8.1.3), which matches to atoms
* [Comment](https://tools.ietf.org/html/rfc5545#section-3.8.1.4), which is a simple text field
* [Geo](https://tools.ietf.org/html/rfc5545#section-3.8.1.6), which maps to a tuple with latitude and longitude

2018-01-14 21:04 UTC, tcitworld commented on lib/icalendar/util/deserialize.ex
> +    |> Enum.map(fn {x, _} -> x end)
I guess this may could improved

2018-01-15 11:14 UTC, lpil requested changes

2018-01-15 11:14 UTC, lpil commented on lib/icalendar/util/deserialize.ex
> +      status: status |> desanitized() |> String.downcase() |> String.to_atom()
Can we remove the `String.to_atom/1` please? Turning random input to atoms is an easy way to leak atoms which can crash the VM.

2018-01-15 11:14 UTC, lpil commented on lib/icalendar/util/deserialize.ex
> +    |> Enum.map(fn {x, _} -> x end)
Fine by me :)

2018-01-15 11:16 UTC, lpil commented
Thanks @tcitworld, this is great. Left some comments :)

2018-01-15 11:24 UTC, tcitworld commented
Fixed :)

2018-01-15 23:49 UTC, lpil commented on test/icalendar/event_test.exs
> +      class: "private"
Why have these been changed?

2018-01-16 12:32 UTC, tcitworld commented on test/icalendar/event_test.exs
> +      class: "private"
My bad

2018-01-17 16:56 UTC, lpil approved these changes
Thanks!

2018-01-17 16:56 UTC, merged

2018-01-17 16:59 UTC, lpil commented
Published a new version, thanks!

2018-01-17 17:34 UTC, tcitworld commented
thank you